config/routes.rb
Rails.application.routes.draw do
  get 'items_imports/new'
  get 'items_imports/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  resources :items
  resources :items_imports
  root "items#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
    validates_presence_of :name
end

app/models/items_import.rb
class ItemsImport
    include ActiveModel::Model
    require 'roo'
  
    attr_accessor :file
  
    def initialize(attributes={})
      attributes.each { |name, value| send("#{name}=", value) }
    end
  
    def persisted?
      false
    end
  
    def open_spreadsheet
      case File.extname(file.original_filename)
      when ".csv" then Csv.new(file.path, nil, :ignore)
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path)
      else raise "Unknown file type: #{file.original_filename}"
      end
    end
  
    def load_imported_items
      spreadsheet = open_spreadsheet
      header = spreadsheet.row(1)
      (2..spreadsheet.last_row).map do |i|
        row = Hash[[header, spreadsheet.row(i)].transpose]
        item = Item.find_by_id(row["id"]) || Item.new
        item.attributes = row.to_hash
        item
      end
    end
  
    def imported_items
      @imported_items ||= load_imported_items
    end
  
    def save
      Item.destroy_all
      if imported_items.map(&:valid?).all?
        imported_items.each(&:save!)
        true
      else
        imported_items.each_with_index do |item, index|
          item.errors.full_messages.each do |msg|
            errors.add :base, "Row #{index + 6}: #{msg}"
          end
        end
        false
      end
    end
  
  end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

    def new
        @item = Item.new
    end

    def create
        @item = Item.new(item_params)
    
        if @item.save
          redirect_to items_path
        else
          render :new, status: :unprocessable_entity
        end
    end

    
    def edit
        @item = Item.find(params[:id])
    end

    def update
        @item = Item.find(params[:id])

        if @item.update(item_params)
            redirect_to items_path
        else
            render :edit, status: :unprocessable_entity
        end
    end
    
  def destroy
    @item = Item.find(params[:id])
    @item.destroy

    redirect_to root_path
  end

  private
  def item_params
    params.require(:item).permit(:name, :quantity)
  end

end

app/controllers/items_imports_controller.rb
class ItemsImportsController < ApplicationController
  def new
    @items_import = ItemsImport.new
  end

  def create
    @items_import = ItemsImport.new(params[:items_import])
    if @items_import.save
      redirect_to items_path
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/items_imports_helper.rb
module ItemsImportsHelper
end

app/views/items/_form.html.erb
<%= form_with model: item do |f| %>
    <div>
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  
    <div>
      <%= f.label :quantity %><br>
      <%= f.text_field :quantity %><br>
    </div><br>
  
    <div>
      <%= f.submit %>
    </div>
  <% end %>
  

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render "form", item: @item %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>
<h2><%=
  link_to 'Download as Excel',
  items_path(format: :xlsx)
%><br></h2>
<h2><%=
  link_to 'Upload from Excel',
  new_items_import_path
%><h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.quantity %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to "Destroy", item_path(item), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h2><%= link_to 'New Item', new_item_path %></h2>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render "form", item: @item %>

app/views/items_imports/create.html.erb
<h1>ItemsImports#create</h1>
<p>Find me in app/views/items_imports/create.html.erb</p>

app/views/items_imports/new.html.erb
<h1>Import Items From Excel</h1>

<p>
Note: Only import spreadsheets that were previously downloaded from this
  application.
</p>

<h3>Requirements</h3>
<ul>
  <li>Here you could list the validations you have in place for your model</li>
  <li>That way your user has a better chance of successful import</li>
</ul>

<h5>Select File</h5>
<%= form_for @items_import do |f| %>
  <% if @items_import.errors.any? %>
    <%= pluralize(@items_import.errors.count, "error") %> prevented us from
    importing your spreadsheet. Please update your spreadsheet and try agin.
    <ul>
      <% @items_import.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
  <%= f.file_field :file %>
  <%= f.submit "Import File" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bulkupload</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>